"""analysis standalone ticker columns

Revision ID: d55899b1e052
Revises: 1e9c13445c12
Create Date: 2026-07-15 19:31:53.507314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55899b1e052'
down_revision: Union[str, Sequence[str], None] = '1e9c13445c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('earnings_analyses', sa.Column('ticker', sa.String(length=10), nullable=True))
    op.add_column('earnings_analyses', sa.Column('fiscal_quarter', sa.String(length=20), nullable=True))
    op.alter_column('earnings_analyses', 'earnings_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Backfill ticker/fiscal_quarter for existing rows from their linked event.
    op.execute("""
        UPDATE earnings_analyses ea
        SET ticker = ee.ticker, fiscal_quarter = ee.fiscal_quarter
        FROM earnings_events ee
        WHERE ea.earnings_event_id = ee.id
    """)

    op.alter_column('earnings_analyses', 'ticker',
               existing_type=sa.String(length=10),
               nullable=False)

    op.create_index(op.f('ix_earnings_analyses_earnings_event_id'), 'earnings_analyses', ['earnings_event_id'], unique=False)
    op.create_index(op.f('ix_earnings_analyses_ticker'), 'earnings_analyses', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_analyses_ticker'), table_name='earnings_analyses')
    op.drop_index(op.f('ix_earnings_analyses_earnings_event_id'), table_name='earnings_analyses')
    op.alter_column('earnings_analyses', 'earnings_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('earnings_analyses', 'fiscal_quarter')
    op.drop_column('earnings_analyses', 'ticker')
    # ### end Alembic commands ###
